I use `monitoring_last_backup.py` with [py3status](https://github.com/ultrabug/py3status). It shows `B:3` when my last backup was 3 days ago.
You can run `python3 monitoring_last_backup.py` to test it.
